language: java
jdk:
    - oraclejdk8
cache:
  directories:
  - .autoconf
  - $HOME/.m2
  timeout: 600
addons:
  sonarcloud:
    organization: "tharindu-bandara"
    token:
      secure: "QjYQreMN1Ass8MW0zeMXKVlZWkKcR3+zk7EaQnvxCSIHt7OY4za8d5aY04oLUnhy2Kvsob0z9QD/kANdlOUtzvEiQjAxulPDD2YMRgHhKo5PJdNT3XV9WGtiwn1cBygJAeARbvjHDyXjisovo4IEWu07YhVl8mfugsWvNL1cBVs/eENhpVHfXPZ6mRG8Xl07bvcEG+pTCKs4+cpLr14oIYDPxxshNthqiGpPKfm6dOTM3y1LKaOBoJjIDh3+iu//jhE5ch4HKRyrj9p/wqWbXvwWiUkHotNYQVUTul0b969VUwBglVSKSytFXEDZo4zyHt1X06VPtyLQYbz2ccRInPciGsx+9AwhRzxsbiUEfkhJTTepJUzdFtQryEejhnHpStx/rKO6JjXm0ECSVmSO/nmAkjqJitEwlx1VPTmIGlNaaTR4UGivxh798VA1tU4caXzpA/dSIj0xW+NzyDPVZBIAAEh1LZg9JeQbzm/KFGmyhA+d8W0UIKOc+7XRJGCGV9KAkrl8NHNbpVTuar/+QPMnqEHWboB8qVE2MAH1eo9fZ/h097tQtvAsaTe8wflnMciZtF3nPbDbDl/LzuSjZyANn0ExzF4VdfDMPs4XKh2TdOIweKNzM6raqmG6t0leJL6iYyNh2uH1dAmpGMCoJe+Uaq8bwYL7ifky/EAdQEY="

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
